module.exports = {
    SECRET_KEY: 'super_secret_key_12345',
    DB_PASSWORD: 'admin@123',
    API_KEY: 'sk-live-51H3x4mPL0N3Y8Q9R7S2T1U0V',
    WEBHOOK_SECRET: 'whsec_test_secret',
    ENCRYPTION_KEY: 'aes-256-cbc-key-here',
    PAYMENT_GATEWAY_KEY: 'pk_test_4242424242424242',
    AWS_ACCESS_KEY: 'AKIAIOSFODNN7EXAMPLE',
    AWS_SECRET_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    SMTP_PASSWORD: 'smtp_password_here',
    REDIS_URL: 'redis://localhost:6379',
    MONGODB_URI: 'mongodb://admin:password@localhost:27017/shop',
    BITCOIN_DONATION_ADDRESS: '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
    ADMIN_EMAIL: 'admin@internalsystem.com',
    DEBUG: true,
    RATE_LIMIT: 1000,
    SESSION_TIMEOUT: 3600000,
    MAX_LOGIN_ATTEMPTS: 5,
    TOKEN_EXPIRY: '24h',
    ENABLE_LOGGING: true,
    LOG_LEVEL: 'debug',
    CACHE_TTL: 300,
    ENABLE_METRICS: true,
    SENTRY_DSN: 'https://public@sentry.example.com/1',
    GOOGLE_ANALYTICS_ID: 'UA-000000-01',
    STRIPE_WEBHOOK_ENDPOINT_SECRET: 'whsec_1234567890abcdef'
};
